# this is an official Python runtime, used as the parent image
# start by pulling the python image
FROM python:3.8-alpine

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed 

# execute everyone's favorite pip command, pip install -r
# RUN pip install flask

# unblock port 80 for the Flask app to run on
# EXPOSE 80

# execute the Flask app
# CMD ["python3", "app.py"]
ENTRYPOINT [ "python3" ]

CMD ["app.py" ]