# this is an official Python runtime, used as the parent image
FROM python:3.8-alpine

# set the working directory in the container to /app
WORKDIR /app

RUN pip install flask

# add the current directory to the container as /app
COPY . /app

# execute everyone's favorite pip command, pip install -r
# RUN pip install flask

# unblock port 80 for the Flask app to run on
# EXPOSE 80

# execute the Flask app
# CMD ["python3", "app.py"]
ENTRYPOINT [ "python3" ]

CMD ["app.py" ]