# this is an official Python runtime, used as the parent image
FROM python:3.8.9-slim

# set the working directory in the container to /app
WORKDIR /app

# add the current directory to the container as /app
ADD . /app

# execute everyone's favorite pip command, pip install -r
RUN pip install flask

# unblock port 80 for the Flask app to run on
EXPOSE 80

# execute the Flask app
CMD ["python3", "app.py"]